#!/bin/bash
# Copyright (C) 2015 Arash Shams <xsysxpert@gmail.com>.
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
CONFIGFILE="$HOME/.ssh/config"

if [ ! -f $CONFIGFILE ]; then
    mkdir -p $HOME/.ssh && touch $CONFIGFILE
fi

is_integer() {
    printf "%d" $1 > /dev/null 2>&1
    return $?
}

do_check_names() {
	grep "^Host" $CONFIGFILE | cut -f2- -d " "
	exit 0
}
	
do_add_process() {
    if [[ "$#" -eq 6 || "$#" -eq 4 ]]; then
	name=$2
	username=$3
	hostname=$4
	if [[ -n $6 ]]; then
	    id=$5
	    port=$6
	else
	    port=22
	fi
    elif [[ "$#" -eq 5 ]]; then
	if is_integer $5; then
	    name=$2
	    username=$3
	    hostname=$4
	    port=$5
	    
	else
	    name=$2
	    username=$3
	    hostname=$4
	    id=$5
	    port=22
	fi
    else
	echo "Usage : $0 $1 NAME USERNAME HOSTNAME [IdentityKey] [PORT]"
	exit 1
    fi

    if [[ $(do_check_names | grep --count "^$name$") != 0 ]]; then
	echo "This name is already used. Try again with another name."
	exit 1
    fi
    
    if [ -n "$id" ]; then
	cat << EOB >> $CONFIGFILE
#begin $name
Host $name
	HostName $hostname
	User $username
	Port $port
	IdentityFile $id
#end $name
EOB
    else
	cat << EOB >> $CONFIGFILE
#begin $name
Host $name
	HostName $hostname
	User $username
	Port $port
#end $name
EOB
    fi
    exit 0
}

do_remove_process() {
    if [ "$#" != 2 ]; then
	echo "Usage : $0 $1 NAME"
	exit 1
    fi
    name=$2
    if [[ $(do_check_names | grep --count "^$name$") != 0 ]]; then
    	sed -ie "/^\#begin $name$/,/^\#end $name$/d" $CONFIGFILE
    	exit 0
    else
	echo "Sorry, \"$name\" is not in list"
    fi
}

do_list_process() {
    if [ -n "$2" ]; then
     	name=$2
	if [[ $(do_check_names | grep --count "^$name$") != 0 ]]; then
    		awk '/^#begin '"$name"'/{Infos="";next}/^#end '"$name"'/{ print Infos;next}{Infos = Infos ($1~/^Host$/ ? "" : "\t") $1 ": " $2}' $CONFIGFILE
		exit 0
	else
		echo "Sorry, \"$name\" is not in list"
		exit 1
	fi
    else
    	awk '/^#begin/{Infos="";next}/^#end/{ print Infos;next}{Infos = Infos ($1~/^Host$/ ? "" : " ") $1 ": " $2}' $CONFIGFILE
    fi
}

do_show_usage() {
	echo -e "Add a new Host: sshconfig add/-a/a NAME USERNAME HOSTNAME [IdentityKey] [PORT] "
	echo -e "Remove a Host: sshconfig remove/-r/r  NAME"
	echo -e "List all exist hosts: sshconfig list/ls/show"
	echo -e "Print Version and info: sshconfig version/-v/v/-V"
	echo -e "Print this message and exit: sshconfig help/-h/h"
}

do_show_version() {
	echo "Create by Arash Shams <xsysxpert@gmail.com>" 
	echo "Version 1.5 Stable"
	echo "Fork me at Github <https://github.com/Ara4Sh/sshconfig>"
}

action=$1
case $action in
	add | -a | a)
	    do_add_process $@
	    ;;
	remove | -r | r)
	    do_remove_process $@
	    ;;
	list | ls | show)
	    do_list_process $@
	    ;;
	version | -v | v | -V)
	    do_show_version $@
	    ;;
	help | -h | h)
	    do_show_usage $@
	    ;;
	*)
	    do_show_usage
	    echo ""
	    do_show_version
	    ;;
esac
